# Site settings
title: Concoctions of a Pixel Artist
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Avidly attempting to pixel paint the world with awkward images,
  ushering away offendingly languid words and the musings of a 
  front-stack developer, designer and artist. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rockstarartist.github.io/" # the base hostname & protocol for your site
github_username:  rockstarartist

# Build settings
markdown: kramdown
